# General settings
dataset_name: "EuroSAT"
data_dir: "./data/EuroSAT/2750/"
save_path: "./outputs/"
seed: 42

# Split settings
num_classes: 10
train_ratio: 0.8
val_ratio: 0.2
percentage_per_class: 0.3

# Training settings
batch_size: 32
num_epochs: 10
lr: 0.001
weight_decay: 0.05

# Learning rate scheduler
use_scheduler: false

